# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb498be891f3a37f3bd971197e299ea4d9c7868fe7fa4ab354328c5eef045cb3226cbc52f6d176ba9a7873c82055d6d17184fe339e657e178430b790bdcd3b81

test:
  secret_key_base: 738ad6f293897874d10d711fb86ddd65ded8f9952e15a7b5e983cf2fae98adc2070d48b740690c17c1561c561f92b077639ff7c7247717a9735bf57f7abda247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
